import React from 'react';
import { createRoot } from 'react-dom/client';
import { flushSync } from 'react-dom';
import { ConnectionContext, WalletContext } from '@solana/wallet-adapter-react';
import { WalletModalProvider } from '@solana/wallet-adapter-react-ui';
import { PublicKey } from '@solana/web3.js';
import { LaunchSigner } from '../../components/launch-wallet';
import '../../app/launch.css';

const creator = '11111111111111111111111111111111';
const other = 'So11111111111111111111111111111111111111112';
const artifact = { schemaVersion: 1, id: 'local-launch', revision: 1, kind: 'create', network: 'devnet', genesisHash: 'genesis', blockhash: 'blockhash', lastValidBlockHeight: 100, mint: other, creator, treasury: null, name: 'Pepe & Chad', symbol: 'INTER', metadataUri: 'https://example.com/token.json', buyLamports: '1000000000', maxTotalLamports: '1200000000', estimatedTotalLamports: '1100000000', quotedTokens: '1000000', transaction: 'placeholder', messageHash: 'hash' };
let reviews = 0, signatures = 0, downloads = 0, revoked = 0;
const connection = { rpcEndpoint: 'http://127.0.0.1:3315/api/rpc' };
let signer = async transaction => { signatures++; return { ...transaction, signed: true }; };
const adapter = { name: 'Fixture wallet', icon: '', supportedTransactionVersions: new Set([0]), publicKey: new PublicKey(creator) };
let wallet = { publicKey: new PublicKey(creator), connected: true, connecting: false, disconnecting: false, wallet: { adapter, readyState: 'Installed' }, wallets: [], select() {}, connect: async () => {}, disconnect: async () => {}, signTransaction: transaction => signer(transaction) };
window.launchHarness = {
  review: async raw => { reviews++; if (raw.invalid) throw Error('Transaction message does not match the prepared artifact.'); return { artifact: { ...artifact, ...raw }, transaction: { version: 0 } }; },
  envelope: (value, transaction) => { if (!transaction.signed) throw Error('Missing signature.'); return { id: value.id, revision: value.revision, transaction: 'signed' }; },
};
const originalReview = window.launchHarness.review;
const realCreate = URL.createObjectURL.bind(URL), realRevoke = URL.revokeObjectURL.bind(URL);
URL.createObjectURL = blob => { downloads++; return realCreate(blob); };
URL.revokeObjectURL = url => { revoked++; return realRevoke(url); };
HTMLAnchorElement.prototype.click = function () { window.lastLaunchDownload = this.download; };
const checks = [];
const check = (ok, message) => { checks.push({ pass: !!ok, message }); if (!ok) throw Error(message); };
const wait = ms => new Promise(resolve => setTimeout(resolve, ms));
const until = async predicate => { for (let i = 0; i < 300; i++) { if (predicate()) return; await wait(10); } throw Error('Timed out waiting for signing state: ' + host.textContent); };
const host = document.getElementById('root');
const root = createRoot(host);
const render = () => flushSync(() => root.render(<ConnectionContext.Provider value={{ connection }}><WalletContext.Provider value={wallet}><WalletModalProvider><LaunchSigner /></WalletModalProvider></WalletContext.Provider></ConnectionContext.Provider>));
const upload = async data => {
  const input = host.querySelector('input[type="file"]');
  const transfer = new DataTransfer(); transfer.items.add(new File([typeof data === 'string' ? data : JSON.stringify(data)], 'prepared.json', { type: 'application/json' }));
  input.files = transfer.files; input.dispatchEvent(new Event('change', { bubbles: true })); await wait(20);
};
const button = () => host.querySelector('.launch-action');
const agree = () => { const input = host.querySelector('input[type="checkbox"]'); if (!input.checked) input.click(); };
window.launchChecks = (async () => {
  render(); check(button().disabled, 'Signing starts disabled without a prepared transaction');
  await upload('x'.repeat(65537)); await until(() => host.querySelector('[role="alert"]'));
  check(reviews === 0 && host.textContent.includes('64 KiB'), 'Oversized files are rejected before transaction review');
  await upload({ invalid: true }); await until(() => host.textContent.includes('does not match'));
  check(button().disabled, 'A rejected transaction cannot be signed');
  await upload({}); await until(() => host.textContent.includes(artifact.mint));
  check(host.textContent.includes('1.2 SOL') && host.textContent.includes('1.1 SOL') && host.textContent.includes('1 SOL'), 'Review shows the initial buy, estimate and total cap');
  agree(); await wait(0); check(!button().disabled, 'Reviewed artifact and matching capable wallet enable sign-only action');
  const before = reviews; button().click(); await until(() => downloads === 1);
  check(reviews === before + 1 && signatures === 1, 'Signing reruns transaction review immediately before requesting the wallet signature');
  check(window.lastLaunchDownload === 'launch-local-launch-1.signed.json', 'Signing downloads a versioned signed envelope');
  await until(() => revoked === 1); check(revoked === downloads, 'Downloaded blob URLs are revoked');
  wallet = { ...wallet, publicKey: new PublicKey(other) }; render(); await wait(0);
  check(button().disabled && host.textContent.includes('creator'), 'A different wallet cannot sign the artifact');
  wallet = { ...wallet, publicKey: new PublicKey(creator), wallet: { ...wallet.wallet, adapter: { ...adapter, supportedTransactionVersions: new Set(['legacy']) } } }; render(); await wait(0);
  check(button().disabled && host.textContent.includes('version 0'), 'A legacy-only wallet is blocked');
  wallet = { ...wallet, wallet: { ...wallet.wallet, adapter }, signTransaction: undefined }; render(); await wait(0);
  check(button().disabled, 'A wallet without signTransaction is blocked');
  wallet = { ...wallet, signTransaction: transaction => signer(transaction) }; render(); await wait(0);
  signer = async () => { throw Error('User rejected the request.'); };
  agree(); await wait(0); button().click(); await until(() => host.textContent.includes('User rejected'));
  check(downloads === 1, 'Wallet rejection is visible and does not download a signed artifact');
  let release;
  window.launchHarness.review = raw => new Promise(resolve => { release = async () => resolve(await originalReview(raw)); });
  await upload({ name: 'Stale file' }); await until(() => release);
  window.launchHarness.review = originalReview;
  await upload({ name: 'Current file' }); await until(() => host.textContent.includes('Current file'));
  await release(); await wait(20);
  check(!host.textContent.includes('Stale file'), 'A replaced file cannot be overwritten by a late review');
  signer = transaction => new Promise(resolve => { release = () => resolve({ ...transaction, signed: true }); });
  release = undefined; agree(); await wait(0); button().click(); await until(() => release);
  wallet = { ...wallet, publicKey: new PublicKey(other) }; render(); await wait(0);
  release(); await wait(20);
  check(downloads === 1, 'A late signature after the connected wallet changes is discarded');
  wallet = { ...wallet, publicKey: new PublicKey(creator) }; render(); await wait(0);
  await upload({}); await until(() => host.textContent.includes(artifact.name));
  return checks;
})().catch(error => ({ error: error.message, checks }));
window.launchChecks.then(result => document.getElementById('results').textContent = JSON.stringify(result, null, 2));
