#!/usr/bin/env node
// Prepare both conditioning images on H3 Turbo's native canvas before uniform 1080P scaling.
// Requires ffmpeg. Uploads the prepared stills to fal; does not generate video.
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { readFile, writeFile } from 'node:fs/promises';
import { fal, falKey } from './fal.mjs';
import { avif } from './site-images.mjs';

const sha256 = (bytes) => createHash('sha256').update(bytes).digest('hex');
const key = await falKey();
// The uncropped originals were uploaded to fal once, when the stills were branded
// (character-assets.json). The tailor edits that same 1376×768 still, so its URL travels
// with the frames; the hash check proves the URL is this file and not an older cut.
const { sources } = JSON.parse(await readFile('character-assets.json', 'utf8'));
const frames = {};
for (const [role, name] of [
  ['host', 'pepe'],
  ['guest', 'gigachad'],
]) {
  const original = `public/${name}-cartoon.png`;
  const originalSha256 = sha256(await readFile(original));
  const originalUrl = sources[`${name}-cartoon`];
  if (typeof originalUrl !== 'string' || !originalUrl.startsWith('https://'))
    throw Error(`No fal URL for ${name}-cartoon in character-assets.json`);
  const remote = await fetch(originalUrl, { signal: AbortSignal.timeout(30000) });
  if (!remote.ok) throw Error(`Could not fetch ${originalUrl}: ${remote.status}`);
  const remoteSha256 = sha256(Buffer.from(await remote.arrayBuffer()));
  if (remoteSha256 !== originalSha256)
    throw Error(
      `${originalUrl} is not ${original}: sha256 ${remoteSha256} vs ${originalSha256}`,
    );
  const image = `/${name}-video.png`;
  // Fit without stretching, then center-crop. Current stills lose only 16 pixels on each side.
  execFileSync('ffmpeg', [
    '-v',
    'error',
    '-i',
    original,
    '-vf',
    'scale=1344:768:force_original_aspect_ratio=increase,crop=1344:768',
    '-frames:v',
    '1',
    '-y',
    `public${image}`,
  ]);
  // The same frame as AVIF, for the pages that merely display it. The PNG below is the one
  // fal conditions on, so it must stay a pixel-exact PNG; the poster is ~30x smaller and is
  // what a phone downloads when someone opens a pasted link.
  const poster = `/${name}-video.avif`;
  await avif(`public${image}`, `public${poster}`);
  const bytes = await readFile(`public${image}`);
  const upload = await fal(
    'https://rest.fal.ai/storage/upload/initiate?storage_type=fal-cdn-v3',
    key,
    {
      file_name: `${name}-video.png`,
      content_type: 'image/png',
    },
  );
  if (!upload.upload_url || !upload.file_url)
    throw Error(`No upload URL for ${role}`);
  const result = await fetch(upload.upload_url, {
    method: 'PUT',
    headers: { 'Content-Type': 'image/png' },
    body: bytes,
  });
  if (!result.ok) throw Error(`Upload failed for ${role}: ${result.status}`);
  frames[role] = {
    image,
    poster,
    source: upload.file_url,
    width: 1344,
    height: 768,
    original,
    originalUrl,
    originalSha256,
  };
  console.log(`${role}: prepared and uploaded 1344×768 frame`);
}
await writeFile(
  'lib/video-frames.ts',
  `// Generated by node scripts/video-frames.mjs. Keep conditioning and native video geometry identical.\nexport const videoFrames = ${JSON.stringify(frames, null, 2)} as const;\n`,
);
