#!/usr/bin/env node
// Prepare both conditioning images on H3 Turbo's native canvas before uniform 1080P scaling.
// Requires ffmpeg. Uploads the prepared stills to fal; does not generate video.
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { readFile, writeFile } from 'node:fs/promises';
import { fal, falKey } from './fal.mjs';

const key = await falKey();
const frames = {};
for (const [role, name] of [
  ['host', 'pepe'],
  ['guest', 'gigachad'],
]) {
  const original = `public/${name}-cartoon.png`;
  const image = `/${name}-video.png`;
  // Fit without stretching, then center-crop. Current stills lose only 16 pixels on each side.
  execFileSync('ffmpeg', [
    '-v',
    'error',
    '-i',
    original,
    '-vf',
    'scale=1344:768:force_original_aspect_ratio=increase,crop=1344:768',
    '-frames:v',
    '1',
    '-y',
    `public${image}`,
  ]);
  // The same frame as WebP, for the pages that merely display it. The PNG below is the one
  // fal conditions on, so it must stay a pixel-exact PNG; the poster is ~20x smaller and is
  // what a phone downloads when someone opens a pasted link.
  const poster = `/${name}-video.webp`;
  execFileSync('ffmpeg', [
    '-v', 'error', '-i', `public${image}`, '-quality', '82', '-y', `public${poster}`,
  ]);
  const bytes = await readFile(`public${image}`);
  const upload = await fal(
    'https://rest.fal.ai/storage/upload/initiate?storage_type=fal-cdn-v3',
    key,
    {
      file_name: `${name}-video.png`,
      content_type: 'image/png',
    },
  );
  if (!upload.upload_url || !upload.file_url)
    throw Error(`No upload URL for ${role}`);
  const result = await fetch(upload.upload_url, {
    method: 'PUT',
    headers: { 'Content-Type': 'image/png' },
    body: bytes,
  });
  if (!result.ok) throw Error(`Upload failed for ${role}: ${result.status}`);
  frames[role] = {
    image,
    poster,
    source: upload.file_url,
    width: 1344,
    height: 768,
    original,
    originalSha256: createHash('sha256')
      .update(await readFile(original))
      .digest('hex'),
  };
  console.log(`${role}: prepared and uploaded 1344×768 frame`);
}
await writeFile(
  'lib/video-frames.ts',
  `// Generated by node scripts/video-frames.mjs. Keep conditioning and native video geometry identical.\nexport const videoFrames = ${JSON.stringify(frames, null, 2)} as const;\n`,
);
